spring:
  application:
    name: userdb-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:news_aggregator}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: "${DB_PASSWORD:Mihu@08}"

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true