server:
  port: 8083

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:news_aggregator}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: "${DB_PASSWORD:Mihu@08}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:no.reply.icebutton@gmail.com}
    password: ${SMTP_PASSWORD:zbog oxbd tbzf cvvh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-for-news-aggregator-2024}
  expiration: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.newsaggregator.auth: DEBUG
    org.springframework.security: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true



# # server:
# #   port: 8081

# # spring:
# #   application:
# #     name: auth-service
# #   datasource:
# #     url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:news_aggregator}?allowPublicKeyRetrieval=true&useSSL=false
# #     username: ${DB_USERNAME:root}
# #     password: "${DB_PASSWORD:root}"
# #     driver-class-name: com.mysql.cj.jdbc.Driver
# #   jpa:
# #     hibernate:
# #       ddl-auto: update
# #     show-sql: false
# #     properties:
# #       hibernate:
# #         dialect: org.hibernate.dialect.MySQL8Dialect
# #         format_sql: true
# #   mail:
# #     host: ${SMTP_HOST:smtp.gmail.com}
# #     port: ${SMTP_PORT:587}
# #     username: ${SMTP_USERNAME:no.reply.icebutton@gmail.com}
# #     password: ${SMTP_PASSWORD:zbog oxbd tbzf cvvh}
# #     properties:
# #       mail:
# #         smtp:
# #           auth: true
# #           starttls:
# #             enable: true

# # jwt:
# #   secret: ${JWT_SECRET:your-super-secret-jwt-key-for-news-aggregator-2024}
# #   expiration: 86400000 # 24 hours

# # management:
# #   endpoints:
# #     web:
# #       exposure:
# #         include: health,info
# #   endpoint:
# #     health:
# #       show-details: always

# # logging:
# #   level:
# #     com.newsaggregator.auth: DEBUG
# #     org.springframework.security: DEBUG 


# # server:
# #   port: 8081

# # spring:
# #   application:
# #     name: auth-service
# #   datasource:
# #     url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:news_aggregator}?allowPublicKeyRetrieval=true&useSSL=false
# #     username: ${DB_USERNAME:root}
# #     password: "${DB_PASSWORD:root}"
# #     driver-class-name: com.mysql.cj.jdbc.Driver
# #   jpa:
# #     hibernate:
# #       ddl-auto: update
# #     show-sql: false
# #     properties:
# #       hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
# #       hibernate.format_sql: true
# #   mail:
# #     host: ${SMTP_HOST:smtp.gmail.com}
# #     port: ${SMTP_PORT:587}
# #     username: ${SMTP_USERNAME:no.reply.icebutton@gmail.com}
# #     password: ${SMTP_PASSWORD:zbog oxbd tbzf cvvh}
# #     properties:
# #       mail:
# #         smtp:
# #           auth: true
# #           starttls:
# #             enable: true

# # jwt:
# #   secret: ${JWT_SECRET:your-super-secret-jwt-key-for-news-aggregator-2024}
# #   expiration: 86400000 # 24 hours

# # management:
# #   endpoints:
# #     web:
# #       exposure:
# #         include: health,info
# #   endpoint:
# #     health:
# #       show-details: always

# # logging:
# #   level:
# #     com.newsaggregator.auth: DEBUG
# #     org.springframework.security: DEBUG


# server:
#   port: 8081

# spring:
#   application:
#     name: auth-service

#   datasource:
#     url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:news_aggregator}?allowPublicKeyRetrieval=true&useSSL=false
#     username: ${DB_USERNAME:root}
#     password: "${DB_PASSWORD:root}"
#     driver-class-name: com.mysql.cj.jdbc.Driver

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: false
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL8Dialect
#         format_sql: true  # ✅ Correct format with nesting

#   mail:
#     host: ${SMTP_HOST:smtp.gmail.com}
#     port: ${SMTP_PORT:587}
#     username: ${SMTP_USERNAME:no.reply.icebutton@gmail.com}
#     password: ${SMTP_PASSWORD:zbog oxbd tbzf cvvh}
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true

# jwt:
#   secret: ${JWT_SECRET:your-super-secret-jwt-key-for-news-aggregator-2024}
#   expiration: 86400000  # 24 hours in ms

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info
#   endpoint:
#     health:
#       show-details: always

# logging:
#   level:
#     com.newsaggregator.auth: DEBUG
#     org.springframework.security: DEBUG

# # eureka:
# #   client:
# #     service-url:
# #       defaultZone: http://localhost:8761/eureka
# #   instance:
# #     prefer-ip-address: true

# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka


# eureka:
#   instance:
#     lease-renewal-interval-in-seconds: 10
#     lease-expiration-duration-in-seconds: 30


