
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dummydb
    username: dummyuser
    password: dummypassword
    jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: dummysecretkey
  expiration: 3600000



#   instance:
#     lease-renewal-interval-in-seconds: 10
#     lease-expiration-duration-in-seconds: 30


