server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/api/news/**

        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/api/activities/**

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
